### ISSUE TITLE
Duplicate Bookshelf API - 1.7.10

### ISSUE THREAD

**Issue by CeterPushing** [TeamBR-Modding/Bookshelf#12]
Forge Mod loader has found a problem with your Minecraft installation
You have mod sources that are duplicate within your system
Mod ID : File name
bookshelf: Bookshelf-1.7.10-1.0.4.187.jar
bookshelf: Bookshelf-1.7.10-1.2.0.jar

I see something from late 2015 about this and there was change published, however either 1.7.10 did not get the commit or it was overlooked for the Mod ID change, is this something that can be addressed?

Thank You

Update: I can see the commit changes in master branch:
  "modid": "bookshelfapi",
  "name": "Bookshelf",

1.7.10 Branch:
  "modid": "bookshelf",
  "name": "Bookshelf",

**Comment by pauljoda** [comment]
We have unfortunatly not been concerned with the 1.7.10 branch for years now. This is an issues that has since been resolved. We did not want to have to change all our mods from the past for an issues we solved in the future. I hope you understand.

Thanks

**Comment by juniorjunior** [comment]
@CeterPushing Depending on which mod you are using which requires this Bookshelf API mod it is possible to make the required changes to get things working together. For example, I was using Modular Systems for 1.7.10 which required Bookshelf(API) along with Enchanting Plus which requires Bookshelf. I was able to get BookshelfAPI-1.7.10 code and ModularSystems-1.7.10 code, modify them both to reference an updated modid for BookshelfAPI and they work just fine.

Just putting this in here for other people since I found this from a google search while trying to resolve this exact issue. Feel free to poke me for and update if you aren't able to manage it on your own.
